dist: xenial
language: python
python:
  - "3.7.6"

install:
  - pip install -r requirements.txt
  - pip install tables
  - pip install importlib-metadata --upgrade
  - python setup.py install

before_script:
  - eggpath='/home/travis/virtualenv/python3.7.6/lib/python3.7/site-packages/MICA-1.0.0-py3.7.egg/MICA/bin/'
  - chmod -R 755 $eggpath
  - chmod -R 755 .
  - git clone https://github.com/snap-stanford/snap
  - cd snap/examples/node2vec
  - make
  - cp node2vec ~/virtualenv/python3.7.6/bin
  - cd -

script:
  - travis_wait 30 ./tests/test_MICA_ge_Kolod.sh
  - travis_wait 20 ./tests/test_MICA_ge_Yan.sh
  - travis_wait 10 ./tests/test_calc_ARI.py

#safelist
branches:
  only:
    - master
    - million

notifications:
  email: false
