dist: xenial
language: python
python:
  - "3.7.6"

install:
  - pip install -r requirements.txt
  - pip install tables
  - pip install importlib-metadata --upgrade
  - python setup.py install

before_script:
  - eggpath='/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/MICA-1.0.0-py3.7.egg/MICA/bin/'
  - chmod -R 755 $eggpath

script:
  - travis_wait 60 ./tests/test_MICA_ge_Kolod.sh

#safelist
branches:
  only:
    - master
    - million

notifications:
  email: false
