dist: xenial
language: python
python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install tables
  - python setup.py install

before_script:
  - eggpath='/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/MICA-0.1.0-py3.6.egg/MICA/bin/'
  - chmod 755 $eggpath/prep.py $eggpath/calc_scatter.py $eggpath/merge_and_norm.py $eggpath/transform.py $eggpath/clustering.py $eggpath/utils.py

script:
  - python -m pytest -v

#safelist
branches:
  only:
    - master
    - develop

notifications:
  email: false
